# Use an official Tomcat image as a parent image
FROM tomcat:9-jdk17

# Remove the default web apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Add the application's WAR file to the container
COPY target/CrudApp-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/CrudApp.war

# Expose the port that Tomcat runs on
EXPOSE 8080