version: "3.8"

services:
  app:
    build: .
    image: spring-boot-mysql-app:latest  # Use this name if you need to tag the built image
    ports:
      - "9090:9090"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/crud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ItsMe
    volumes:
      - /data/springboot-app

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - springboot-db-net
    environment:
      MYSQL_ROOT_PASSWORD: ItsMe
      MYSQL_DATABASE: crud
    volumes:
      - /data/mysql

networks:
  springboot-db-net:

volumes:
  mysql-data: